import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Editorial Guidelines | SnowSense™",
  description: "Read our strict editorial guidelines for ensuring meteorological accuracy and trustworthy reporting.",
  alternates: {
    canonical: "/legal/editorial-guidelines",
  },
};

export default function EditorialGuidelinesPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 md:py-24">
      <h1 className="text-3xl md:text-5xl font-display font-black text-white mb-6">
        Editorial Guidelines
      </h1>
      
      <div className="prose prose-invert prose-blue max-w-none text-zinc-300">
        <p className="lead text-lg text-zinc-400 mb-8">
          At SnowSense™, we are committed to providing our users with highly accurate, unbiased, and data-driven meteorological content. These guidelines establish the core principles that our authors and editorial team follow.
        </p>

        <h2 className="text-2xl font-bold text-white mt-12 mb-4">1. Accuracy & Data Sources</h2>
        <p>
          All weather predictions, blog posts, and educational guides must be based on verifiable meteorological data. We rely exclusively on publicly available, peer-reviewed, or government-issued data sources, primarily including:
        </p>
        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>The National Weather Service (NWS)</li>
          <li>National Oceanic and Atmospheric Administration (NOAA)</li>
          <li>Open-Meteo and associated high-resolution forecast models (HRRR, ECMWF, GFS)</li>
        </ul>
        <p>
          Authors are strictly prohibited from sensationalizing weather events or predicting extreme outcomes without clear, modeled backing from these reputable sources.
        </p>

        <h2 className="text-2xl font-bold text-white mt-12 mb-4">2. Objectivity & Bias</h2>
        <p>
          Our content is purely informational and educational. We do not endorse specific commercial products without clear disclosure, and we maintain strict independence from advertising influence. All editorial decisions are made independently of any sponsored partnerships.
        </p>

        <h2 className="text-2xl font-bold text-white mt-12 mb-4">3. Correction Policy</h2>
        <p>
          Despite our reliance on automated models and expert review, errors can occur. If a factual error is discovered in our editorial content or blog guides, we will promptly update the article and, if necessary, provide a correction note at the top or bottom of the page detailing what was changed and when.
        </p>

        <h2 className="text-2xl font-bold text-white mt-12 mb-4">4. Originality & Plagiarism</h2>
        <p>
          All content published on SnowSense™ must be original. We strictly prohibit plagiarism. While we aggregate data from external APIs, any analysis, synthesis, or educational writing must be generated by our editorial team.
        </p>

        <h2 className="text-2xl font-bold text-white mt-12 mb-4">5. Review Process</h2>
        <p>
          Before any static educational or editorial piece is published on our blog or guides section, it undergoes review by at least one other team member. The review ensures that the content aligns with our persona ("The Empathetic Nerd") — meaning it is precise, accessible, logically sound, and genuinely helpful.
        </p>

        <hr className="my-12 border-zinc-800" />
        
        <p className="text-sm text-zinc-500">
          Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>
      </div>
    </div>
  );
}
